INSERT INTO CASH_CARD(CASH_CARD_ID, AMOUNT, OWNER) VALUES (99, 123.45, 'lorenchess');
INSERT INTO CASH_CARD(CASH_CARD_ID, AMOUNT, OWNER) VALUES (100, 1.00, 'lorenchess');
INSERT INTO CASH_CARD(CASH_CARD_ID, AMOUNT, OWNER) VALUES (101, 150.00, 'lorenchess');
INSERT INTO CASH_CARD(CASH_CARD_ID, AMOUNT, OWNER) VALUES (102, 200.00, 'isaloren');